kind: pipeline
name: default

steps:
- name: build
  image: nginx
#   commands:
#     - mvn clean package
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_password
    repo: t56473333/drone-test
    # 要推送docker地址
    registry: hub.docker.com
    # 使用的docker hub地址
    tags: ${DRONE_BUILD_NUMBER}
    # docker的tag值, 默认每次加1
    insecure: true

trigger:
  branch:
  - main
