kind: pipeline
name: default

steps:
- name: build
  image: nginx
#   commands:
#     - mvn clean package
- name: docker
  image: plugins/docker
  settings:
    dockerfile: .
    username: t56473333
#       from_secret: docker_user
    password: yv5vbw9Mx-mBB:n
#       from_secret: docker_password
    repo: t56473333/drone-test
    # 要推送docker地址
    registry: hub.docker.com
    # 使用的docker hub地址
    tags: ${DRONE_BUILD_NUMBER}
    # docker的tag值, 默认每次加1
    insecure: true
  when:
    event: push
    branch: main
