kind: pipeline
name: default

steps:
- name: dron_test
  image: nginx

# - name: build_image
#   image: plugins/docker
# # 构建docker镜像专用镜像
#   volumes:
#   - name: docker
#   # 挂载下面定义的Volumn
#     path: /var/run/docker.sock
#     # 与宿主机用同一docker
#     settings:
#     # plugins/docker用到的相关配置
#       username: 
#         from_secret: docker_user
#         # alicloud指定的docker hub的用户名(前面配置)
#       password: 
#         from_secret: docker_password
#         # alicloud指定的docker hub的密码(前面配置)
#       repo: t56473333/drone-test
#       # 要推送docker地址
#       registry: hub.docker.com
#       # 使用的docker hub地址
#       tags: ${DRONE_BUILD_NUMBER}
#       # docker的tag值, 默认每次加1
